#set false to disable auto-updating
auto-update: true

#Sign setting
sign: '&0[Tutorial]'

#Set to true to make those that are new to server to join a tutorial and which tutorial to make them join
first_join: false
first_join_tutorial: 'tutorial'

#rewards. Money Rewards requires Vault.
rewards: false

#Count Down Timer for tutorial views
exp_countdown: false

#per view eco settings
view_money: "0.00"
view_exp_give: "0.0"

#per tutorial eco settings
tutorial_money: "0.00"
tutorial_exp_give: "0.0"

#Enable/disable for per tutorial rewards
per_tutorial_money: false
per_tutorial_exp: false

#Enable/disable for per view rewards
per_view_money: false
per_view_exp: false
