name: ServerTutorial
main: io.snw.tutorial.ServerTutorial
version: maven-version-number
description: Tutorial plugin
authors: [hawkfalcon, gomeow, Frostalf]
website: snw.io
softdepend: [Vault]
commands:
    tutorial:
        description: tutorial
permissions:
    tutorial.*:
        children:
            tutorial.use: true
            tutorial.create: true
    tutorial.create:
        default: OP
    tutorial.use:
        default: true
    tutorial.config:
        default: OP
